version: '3.7'
services:
  react: 
    build:
      context: . # dockerfile 위치
    container_name: front_server # 컨테이너 이름 설정
    ports:
    # 포트 설장
      - "3001:3000"
    environment:
     # 리로딩 지원 
      - CHOKIDAR_USEPOLLING=true   